# Generated by Django 2.2.19 on 2024-06-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20240620_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='callback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
