# Generated by Django 2.2.19 on 2024-06-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_subject_callback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='text',
        ),
    ]
